baseURL = "https://shilbertsthoughtlab.netlify.app/"
title = "Shilbert's Thought Lab"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "Iâ€™m still figuring out if weâ€™re in a bear or bull market. ğŸ»ğŸ‚"

